# SPDX-License-Identifier: Apache-2.0
# Generated by Django 5.2.17 on 2026-09-03 10:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("cve", "CVE"),
                            ("cwe", "CWE"),
                            ("provider_rule", "Provider rule"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ManualIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("remediation", models.TextField(blank=True)),
                ("reported_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("remediation", models.TextField(blank=True)),
                (
                    "provider_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("not_observed", "Not observed"),
                            ("unknown", "Unknown"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
