# SPDX-License-Identifier: Apache-2.0
# Generated by Django 5.2.17 on 2026-09-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0002_initial"),
        ("findings", "0001_initial"),
        ("integrations", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="current_raw_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="integrations.rawsourcerecord"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="integrations.sourceaccount"
            ),
        ),
        migrations.AddField(
            model_name="findingidentifier",
            name="finding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="findings.finding",
            ),
        ),
        migrations.AddField(
            model_name="manualissue",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="manualissue",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancy.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="manualissue",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
            ),
        ),
        migrations.AddField(
            model_name="manualissue",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["organisation", "status", "last_observed_at"],
                name="findings_org_status_seen_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("source_account", "external_id"), name="findings_source_external_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_observed_at__gte", models.F("first_observed_at"))),
                name="findings_observation_order_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="findingidentifier",
            constraint=models.UniqueConstraint(
                fields=("finding", "identifier_type", "value"), name="findings_identifier_unique"
            ),
        ),
    ]
