# SPDX-License-Identifier: Apache-2.0
# Generated by Django 5.2.17 on 2026-09-03 10:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("correlation_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partially succeeded"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("checkpoint_before", models.TextField(blank=True)),
                ("checkpoint_after", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("security_scorecard", "SecurityScorecard"),
                            ("wiz", "Wiz"),
                            ("tenable", "Nessus / Tenable"),
                            ("csv", "CSV"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawSourceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=500)),
                ("content_sha256", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="integrations.importrun"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="integrations.sourceaccount"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="importrun",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="integrations.sourceaccount"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceaccount",
            constraint=models.UniqueConstraint(
                fields=("organisation", "name"), name="integrations_source_org_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="rawsourcerecord",
            index=models.Index(
                fields=["organisation", "source_account", "external_id"],
                name="integrations_raw_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawsourcerecord",
            constraint=models.UniqueConstraint(
                fields=("source_account", "external_id", "content_sha256"),
                name="integrations_raw_version_unique",
            ),
        ),
    ]
