# SPDX-License-Identifier: Apache-2.0
# Generated by Django 5.2.17 on 2026-09-03 10:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetResolutionCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("cloud_resource_id", "Cloud resource ID"),
                            ("agent_id", "Scanner agent ID"),
                            ("cmdb_id", "CMDB ID"),
                            ("fqdn", "Fully qualified domain name"),
                            ("mac", "MAC address"),
                            ("ip", "IP address"),
                            ("repository_url", "Repository URL"),
                            ("provider_id", "Provider asset ID"),
                        ],
                        max_length=40,
                    ),
                ),
                ("normalized_value", models.CharField(max_length=500)),
                ("context", models.CharField(blank=True, max_length=500)),
                ("candidate_asset_ids", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("cloud_resource", "Cloud resource"),
                            ("application", "Application"),
                            ("repository", "Repository"),
                            ("domain", "Domain"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("canonical_name", models.CharField(max_length=500)),
                ("environment", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.businessunit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("cloud_resource_id", "Cloud resource ID"),
                            ("agent_id", "Scanner agent ID"),
                            ("cmdb_id", "CMDB ID"),
                            ("fqdn", "Fully qualified domain name"),
                            ("mac", "MAC address"),
                            ("ip", "IP address"),
                            ("repository_url", "Repository URL"),
                            ("provider_id", "Provider asset ID"),
                        ],
                        max_length=40,
                    ),
                ),
                ("normalized_value", models.CharField(max_length=500)),
                ("context", models.CharField(blank=True, max_length=500)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="assets.asset",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
                    ),
                ),
            ],
        ),
    ]
