# SPDX-License-Identifier: Apache-2.0
# Generated by Django 5.2.17 on 2026-09-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("integrations", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetalias",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="integrations.sourceaccount",
            ),
        ),
        migrations.AddField(
            model_name="assetresolutioncase",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
            ),
        ),
        migrations.AddField(
            model_name="assetresolutioncase",
            name="resolved_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assetresolutioncase",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="integrations.sourceaccount"
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("organisation", "asset_type", "canonical_name", "environment"),
                name="assets_canonical_identity_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="assetalias",
            index=models.Index(
                fields=["organisation", "alias_type", "normalized_value", "context"],
                name="assets_alias_resolution_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetalias",
            constraint=models.UniqueConstraint(
                fields=("organisation", "alias_type", "normalized_value", "context", "asset"),
                name="assets_alias_asset_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetresolutioncase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("source_account", "alias_type", "normalized_value", "context"),
                name="assets_resolution_open_unique",
            ),
        ),
    ]
