# SPDX-License-Identifier: Apache-2.0
# Generated by Django 5.2.17 on 2026-09-02 23:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditHead",
            fields=[
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="tenancy.organisation",
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                (
                    "event_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("correlation_id", models.UUIDField()),
                ("actor_label", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=150)),
                ("object_type", models.CharField(max_length=150)),
                ("object_id", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("previous_hash", models.CharField(max_length=64)),
                ("event_hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organisation"
                    ),
                ),
            ],
            options={
                "ordering": ("organisation_id", "sequence"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "sequence"), name="audit_event_org_sequence_unique"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION audit_reject_event_mutation() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'audit events are append-only';
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER audit_event_no_update_or_delete
                BEFORE UPDATE OR DELETE ON audit_auditevent
                FOR EACH ROW EXECUTE FUNCTION audit_reject_event_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS audit_event_no_update_or_delete ON audit_auditevent;
                DROP FUNCTION IF EXISTS audit_reject_event_mutation();
            """,
        ),
    ]
